version: "3"
services:
  app:
    container_name: "goapp"
    image: golang:1.16
    volumes:
      - ./:/code
    tty: true
    stdin_open: true
    build:
        context: .
        dockerfile: build/Dockerfile
    environment:
      - PORT
      - DRIVER
      - DSN
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db-dev

  db-dev:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    container_name: db-dev
    restart: always
    volumes:
      - data-dev:/var/lib/mysql
    
volumes:
  data-dev:
    driver: local
  # mysql:
  #   build: ./mysql/
  #   volumes:
  #         # 初期データを投入するSQLが格納されているdir
  #         # - ./mysql/init:/docker-entrypoint-initdb.d
  #         # 永続化するときにマウントするdir
  #       - ./mysql/data:/var/lib/mysql
  #   environment: 
  #       - MYSQL_ROOT_PASSWORD=golang
  #   ports:
  #       - "3306:3306"