version: "3"
services:
  app:
    container_name: "app"
    image: golang:1.16
    volumes:
      - ./:/code
    tty: true
    build:
        context: .
        dockerfile: build/Dockerfile
    ports:
        - 3000:3000